name: Run tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:

  build:
    steps:
      - name: Update gcc/g++
        runs-on: [ubuntu-latest, windows-latest]
        run: |
          echo Updating gcc/g++
          sudo apt-get update
          sudo apt-get install -y gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90

      - name: Build
        run: |
          echo Building
          cmake -S . -B Build
          cd Build
          make
          cd ..

  test:
    needs: build    
    steps:
      - name: Run tests
        runs-on: [ubuntu-latest, windows-latest]
        run: |
          echo Running tests
          cd bin
          ./tests

          
