name: Run tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:

  system_update:
    runs-on: ubuntu-latest
    steps:
      - name: Update system
        run: |
          echo Updating system
          sudo apt-get update

    steps:
      - name: Update gcc/g++
        run: |
          sudo apt-get install -y cmake
          echo Updating gcc/g++
          sudo apt-get install -y gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90


  build:
  `needs: system_update`
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Build
        run: |
          echo Building
          cmake -S . -B Build
          cd Build
          make
          cd ..

  test:
    needs: build    
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo Running tests
          cd bin
          ./tests

          
