name: Run tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update gcc/g++
        run: |
          echo Updating gcc/g++
          touch test.txt
          sudo apt-get update
          sudo apt-get install -y gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90

      - name: Build
        run: |
          echo Building
          ls -la
          pwd
          cd ..
          ls -la
          cmake -S . -B Build
          cd Build
          make
          cd ..

  test:
    needs: build    
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo Running tests
          cd bin
          ./tests

          
