name: Run tests

on:
  push:
    branches:
      - github-actions-tests-Maxime
  pull_request:
    branches:
      - main
      - dev

jobs:

  system_update:
    runs-on: ubuntu-latest
    steps:
      - name: Update system
        run: |
          echo Updating system
          sudo apt-get update
          sudo apt-get install -y cmake
          sudo apt-get install -y gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90
          
      - name: Repository clone
        run:
          echo Cloning repository
          type: git-clone
          title: Step Title
          description: Step description
          working_directory: /path
          repo: owner/repo
          git: my-git-provider
          revision: abcdef12345'
          use_proxy: false
          credentials:
            username: user
            password: credentials
          fail_fast: false
          strict_fail_fast: true
          when:
            branch:
              ignore: [ develop ]
          on_success:
            ...
          on_fail:
            ...
          on_finish:
            ...
          retry:
            ...  



  build:
    needs: system_update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build
        run: |
          echo Building
          cmake -S . -B Build
          cd Build
          make
          cd ..

  test:
    needs: build    
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo Running tests
          cd bin
          ./tests
